version: '3.7'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=eva
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=eva
      - MYSQL_PASSWORD=pass
    expose:
      - 3306
    
    ports:
      - 3306:3306

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8082:80
    links:
      - mysql:eva
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root

